# Generated by Django 4.1.5 on 2023-02-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wampAudits', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=75),
        ),
    ]
