# Generated by Django 4.1.5 on 2023-02-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wampAudits', '0003_article_article_picture_topic_cover_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/wampAudits/img'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/wampAudits/img'),
        ),
    ]
