# Generated by Django 4.1.5 on 2023-02-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wampAudits', '0004_alter_article_article_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_picture',
            field=models.ImageField(blank=True, null=True, upload_to='wampAudits/img'),
        ),
    ]
