# Generated by Django 4.1.5 on 2023-02-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wampAudits', '0006_alter_article_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
