# Generated by Django 4.1.5 on 2023-02-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wampAudits', '0007_alter_topic_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='wampAudits.topic'),
        ),
    ]
