# Generated by Django 4.1.5 on 2023-02-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wampAudits', '0009_remove_comment_article_reply_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wampAudits.comment'),
        ),
    ]
