# Generated by Django 4.1.5 on 2023-04-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wampAudits', '0010_alter_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='owner_name',
            new_name='name',
        ),
    ]
